### ISSUE TITLE
Unable to get code

### ISSUE THREAD

**Issue by daniel-main** [Kentico/xperience-training-13#103]
### Brief bug description

Attempting to download the code is currently giving this error when attempting to do it via the Git client:

Cloning into 'C:\Users\maind\Documents\GitHub\xperience-training-13'...
error: RPC failed; HTTP 502 curl 22 The requested URL returned error: 502
fatal: error reading section header 'shallow-info'

### Repro steps

1. Go to any of the branches
2. Click on Code button
3. Select Open with GitHub desktop, or any of the other options

### Expected behavior

Down loading the code

### Additional context

Not sure if this is a Git Hub issue,  or something with the repos them selves.  just thought I would bring it to your attention.

**Comment by eugene-cp** [comment]
I tried cloning just now and it works ok, must be just a temporary github issue.

![image](https://user-images.githubusercontent.com/22228592/205184673-2356d62a-9c20-412c-b36a-728c9f155f94.png)

**Comment by JanLenoch** [comment]
Hi @eugene-cp, thanks for stepping in! Cloning works without hiccups on my side, too -> closing.
