### ISSUE TITLE
Create an IStringLocalizer for data annotation attributes

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/xperience-training-13#55]
### Who

- [ ] Anonymous visitor
- [ ] Patient
- [ ] Doctor
- [x] Content editor
- [ ] Marketer
- [ ] Administrator
- [x] Developer

### Needs what

To localize texts on the live site via the Localization application. Therefore, they need a way to fetch the resource strings in the code, including the DataAnnotations attributes.

Thus, we need to create a simple IStringLocalizer implementation (along with its corresponding factory) that in turn calls into ResHelper to provide DataAnnotations attribute instances with localized texts.

### Why

In views, controllers and other ordinary code, the dev can simply call ResHelper. However, in DataAnnotation attribute, we no longer provide the support for resource keys in Core, as we provided for MVC 5.

### Issue expands upon

This issue expands upon another issue(s): #48, #49 

### Reference

* https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1#dataannotations-localization
* https://github.com/aspnet/Localization/issues/66

**Comment by albertoponcato** [comment]
Hello @JanLenoch and @kentico-ericd, regarding this point we are experiencing a very strange problem, there seems to be some problem when the culture is changed, it seems that the data annotations are not translated going to recover the new culture but always use the first one, which could be the problem?

**Comment by JanLenoch** [comment]
Hello @albertoponcato , thank you for your message. Yes you are right. I noticed that in the early days of the implementation. However, my investigation led me to the framework being the culprit. It seems that the strings are cached somewhere on their way from Xperience to the views, leading to English variants in a Spanish page and vice versa.

I'll revisit the issue when I start developing the next-gen training (on top of .NET 6).

**Comment by albertoponcato** [comment]
Hello @JanLenoch, the problem does not seem to be related to the string cache, the problem is that the wrong culture is passed at [this point](https://github.com/Kentico/xperience-training-13/blob/e1824ef41bfb38d515b36f9a9e9eb2ee383ae8f2/XperienceAdapter/Localization/XperienceStringLocalizer.cs#L43-L44) despite being set correctly on [Thread.CurrentThread.CurrentUICulture](https://github.com/Kentico/xperience-training-13/blob/e1824ef41bfb38d515b36f9a9e9eb2ee383ae8f2/XperienceAdapter/Localization/XperienceStringLocalizer.cs#L15), can you verify?

**Comment by JanLenoch** [comment]
Hello @albertoponcato , sorry for a late reply. I was busy working on a brand new course and recovering from a longer Covid infection.

Thanks for reminding this to me. Yes, you are right. It wasn't the strings but the culture that was cached. And now, upon some research, it seems that there is no elegant way around that problem. When debugging the code, I found that there are multiple `XperienceStringLocalizer` instances used, even when I switch from `InstancePerLifetimeScope` to `InstancePerDependency` in `AutoFacConfig`. It has the following reason: The data annotation attributes, as any other attributes, are recognized using reflection (at runtime). The reflection objects are cached by the framework and AFAIK there's no way to selectively disable the caching. Therefore, the only way to make things work with `System.DataAnnotations` attributes is to resign on storing the culture in the `_cultureName` field and resolve the culture on the fly in the `GetString` method.

I'll commit the updated code soon, along with an updated set of instructions in the course.

Again, thanks for pointing this out!

**Comment by JanLenoch** [comment]
The only problem with the workaround would be to deal with `IStringLocalizer.WithCulture()`. If I want to deal with the original problem, I'd need to throw `NotImplementedException`, which might be dangerous. That member is actually called several times from within MVC assemblies. However, it is (as well as all of its wrappers in the MVC solution) being marked as obsolete.

For now, I resorted to throwing that exception. However, I'm open to other options, @albertoponcato, if you happen to have some.
