### ISSUE TITLE
Basic CTB routing cannot be implemented

### ISSUE THREAD

**Issue by kentico-ericd** [Kentico/xperience-training-13#73]
### Brief bug description

Because `MedioClinic.Models.PageViewModel` is declared in _Layout.cshtml, you cannot create a view for [basic routing](https://docs.xperience.io/developing-websites/implementing-routing/content-tree-based-routing/setting-up-content-tree-based-routing#Settingupcontenttreebasedrouting-BasicSettingupbasicrouting) which requires the `Kentico.Content.Web.Mvc.Routing.IPageViewModel<TPage>` model.

### Repro steps

1. Create a new view in \Views\Shared\PageTypes\MedioClinic_Doctor.cshtml with the code

```
@using CMS.DocumentEngine.Types.MedioClinic
@model Kentico.Content.Web.Mvc.Routing.IPageViewModel<Doctor>
@Model.Page.DocumentName
```

2. Access /en-us/en-us/doctors/jack-sparrow/
3. Error message displayed:

> InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'Kentico.Content.Web.Mvc.Routing.PageViewModel`1[CMS.DocumentEngine.Types.MedioClinic.Doctor]', but this ViewDataDictionary instance requires a model item of type 'MedioClinic.Models.PageViewModel'.

### Expected behavior

Basic CTB routing should work and we should include an example of it

**Comment by JanLenoch** [comment]
The basic CTB routing was designed for nothing but the most basic scenarios. The Medio Clinic solution aims to become more than that.
