### ISSUE TITLE
Errors when running ContinuousIntegration.exe -r

### ISSUE THREAD

**Issue by diger74** [Kentico/xperience-training-13#80]
I've installed fresh Kentico 13 empty website and run ContinuousIntegration.exe -r, but unfortunately there were some errors, log file is attached.
[log.txt](https://github.com/Kentico/xperience-training-13/files/6022310/log.txt)

**Comment by diger74** [comment]
I think I've found the main root of this issue: there are a few URL path items for the same page and culture, for example here:
https://github.com/Kentico/xperience-training-13/tree/master/CMS/App_Data/CIRepository/medioclinic/cms.pageurlpath/contact-us%4012a34c7a10
When you delete duplicates, restore works without any problems

**Comment by FanAttic-dev** [comment]
> I think I've found the main root of this issue: there are a few URL path items for the same page and culture, for example here:
> https://github.com/Kentico/xperience-training-13/tree/master/CMS/App_Data/CIRepository/medioclinic/cms.pageurlpath/contact-us%4012a34c7a10
> When you delete duplicates, restore works without any problems

Thanks, worked like charm.

**Comment by JanLenoch** [comment]
Hi guys, thanks for letting me know about that. Sorry for a late reply, I was off for some time. Fixed through https://github.com/Kentico/xperience-training-13/commit/e58176a260d1759d7abaf91dc35c783cf2f6face .
