### ISSUE TITLE
ContinuousIntergation.exe not found where it says in course notes

### ISSUE THREAD

**Issue by PaulCarter** [Kentico/xperience-training-13#84]
Trying to Populate MedioClinic dbase but notes seem wrong as it says the ContinuousIntergation.exe should be in the CMS\bin folder. it doesn't exist

**Comment by JanLenoch** [comment]
Hello @PaulCarter , in the notes, you'll find only a high-level list of instructions. They are meant to give you just a glimpse of the whole set of steps. The full instructions can be found in the course (they are much more detailed than in the repo's readme).

**Comment by PaulCarter** [comment]
Hi Jan, thank you for the quick response. I am following the detailed
notes. Just confused about the locations etc. Here is a screen shot

[image: image.png]
Regards,

Paul

**Comment by JanLenoch** [comment]
Hi @PaulCarter ,

I'm sorry, you most probably answered from within your mailbox. I cannot see the attached image. However, if you can't find the ContinuousIntegration.exe utility in the CMS/bin folder, you might have missed an instruction in the "Xperience basics, development prerequisites" page to build the WebApp.sln solution first.

Jan

**Comment by PaulCarter** [comment]
Hi jan. it’s me being an idiot. I did not realise the detailed instructions
provided more details using the horizontal sliders. Thank you for your
time. Best regards

**Comment by JanLenoch** [comment]
No problem at all! If you hit any other problem, drop us a line.

Jan

**Comment by PaulCarter** [comment]
Hi jan. not finding nt authority \network.service in in create database
login. Regards paul

**Comment by JanLenoch** [comment]
Your spelling is a bit incorrect: The account name is "NT AUTHORITY\NETWORK SERVICE".

**Comment by PaulCarter** [comment]
I know that's what i put, just difficult to type on mobile, sorry

**Comment by PaulCarter** [comment]
Hi Jan,

Managed to sort out the network services in dbase security/login and set
the owner and public flags I also created a application pool in IIS with an
identity of NetworkService, I then created a virtual app pointing to my
repo CMS folder. The problem i am having now is that when trying to set
security permissions on my CMS folder to set up file system permissions, i
am not seeing the NETWORK SERVICE group, assigned in the IIS. Any
suggestions please

Regards,

Paul Carter

**Comment by JanLenoch** [comment]
Hi Paul,

Great you made progress! This security principal should be looked up using the same system dialog window as in SLQ Server Management Studio.

When in File Explorer, right-click the `CMS` folder and select `Properties`. In the `CMS Properties` window, go to the `Security` tab. Press `Edit...`. In the `Permissions for CMS` dialog, press `Add...`. In the `Select Users, Computers, Service Accounts, or Groups` dialog, type `network service` and press `Check Names`. The principal will be recognized and you should be good to go.

In general, when setting NTFS permissions, this security principal should be always available, no matter which folder you set the permissions on.

Hope it helps.

**Comment by PaulCarter** [comment]
Yes great, thank you

Regards,

Paul

**Comment by PaulCarter** [comment]
hi Jan almost there, I hope. Not finding the ContinuousIntegration.exe in
my CMS bin folder. Just a subfolder called roslyn ?

Regards,

Paul

**Comment by PaulCarter** [comment]
Hi Jan,

Any idea why i cant find the ContinuousIntegration.exe in my CMS bin
folder. I,m just using the repo to browse the project code, so would have
expected it to be in the rep project ?

Regards,

Paul

**Comment by JanLenoch** [comment]
Hi Paul, I was just about to ask if you have built the WebApp.sln solution. You should find the utility there once this solution is built.

**Comment by PaulCarter** [comment]
Hi Jan,

That did the trick , being a bit too cautious. I shall try and get my data
in their now.

Best Regards,

Paul

**Comment by JanLenoch** [comment]
You should not run the WebApp.sln solution from Visual Studio. Once it is built, you should register the /CMS folder in IIS as a virtual application (or a standalone website, if you will).

**Comment by PaulCarter** [comment]
Yes i see. VS places the arbitrary port number at end of localhost.. Ok all
running now. Thank you for your support.

Best Regards,

Paul

**Comment by PaulCarter** [comment]
why dont i have any pages application apart from the tile ?

**Comment by PaulCarter** [comment]
ignore me. I wasn't on the medio site
