### ISSUE TITLE
Hide language prefix in default culture URLs

### ISSUE THREAD

**Issue by phixxo** [Kentico/xperience-training-13#91]
The Medio Clinic project is not respecting the "Hide language prefix in default culture URLs" setting in Settings -> URLs and SEO.  Even when turned ON, the URL is like: _/**en-us**/home_

![ON](https://user-images.githubusercontent.com/17883073/126290517-d7f3075f-5c2e-4600-9764-0080e916aa5c.png)

When turned OFF, then the language prefix is even doubled: _/**en-us/en-us**/home_

![OFF](https://user-images.githubusercontent.com/17883073/126290509-0e20f412-2a04-4f6e-8d91-22326f8d4cc8.png)

It seems that that there is the culture code prefix hardcoded somewhere.

**Comment by JanLenoch** [comment]
Hi @phixxo ,

Thanks for letting me know! I know about the problem and its rootcause. It lies in the ContinuousRepository utility that restores the URL paths with the language prefix, although it should not to.

I have an instruction in the course to fix the problem by temporarily switching from the CTB routing mode to the custom (conventional) and back. This re-generates fresh URL paths.

(The workaround with the "Hide language prefix ..." is not the best one, albeit it works.)
