### ISSUE TITLE
using bug

### ISSUE THREAD

**Issue by bogdan71** [Kentico/xperience-training-13#96]
### Brief bug description

in Top.cshtml file the using should be 
@using MedioClinic.Components.ViewComponents

as explained by the course
currently it is:
@using MedioClinic.ViewComponents

**Comment by JanLenoch** [comment]
Hi @bogdan71 ,

Thanks for your suggestion. However, it stems from the fact that I do not give instructions as to what namespace to put a class into. It is true that the MedioClinic.ViewComponents namespace does not conform to the folder structure. I'll correct that in both the code base and the course.

Jan
